# Fase 1: Construcción (Maven)
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Fase 2: Ejecución
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080

# Usamos las variables de memoria que tenías en Railway
ENTRYPOINT ["java", "-Dserver.port=${PORT}", "-Xms256m", "-Xmx380m", "-XX:+UseSerialGC", "-jar", "app.jar"]