spring.application.name=demo

# Usa la IP pública de tu servidor Hetzner
#spring.datasource.url=jdbc:postgresql://62.238.8.177:5432/backmarket
spring.datasource.url=jdbc:postgresql://renfe-postgres-db:5432/backmarket
spring.datasource.username=admin_renfe
spring.datasource.password=Scottville%7
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path=/api/v1
springdoc.swagger-ui.path=/docs